layouts:
    extensions:
        PaperModExtension: Cecil\Renderer\Extension\PaperModExtension

pages:
    highlight:
        enabled: true

pagination:
    enabled: false

paths:
    -   section: posts
        path: :section/:year/:month/:day-:slug

analytics: false
