#avatar: images/avatar-white.jpg
posts:
  section: posts
analytics: false
pagination:
  enabled: false
pages:
  highlight:
    enabled: true
paths:
  - section: posts
    path: :section/:year/:month/:day-:slug
layouts:
  extensions:
    PaperModExtension: Cecil\Renderer\Extension\PaperModExtension
